development:
  adapter: postgresql
  encoding: unicode
  database: blog_development
  username: darcast 
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: blog_test
  username: darcast
  host: localhost